# Generated by Django 3.2.5 on 2021-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('desc', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('project_image1', models.ImageField(default='SOME IMAGE', upload_to='projects/')),
                ('project_image2', models.ImageField(default='SOME IMAGE', upload_to='projects/')),
                ('project_image3', models.ImageField(default='SOME IMAGE', upload_to='projects/')),
                ('tags', models.ManyToManyField(to='projects.tags')),
            ],
        ),
    ]
